//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGdoc.GestionServRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.EmpresaRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.AccesoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoAccesoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoPrioridadRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoParticipRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoEventoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoOperacionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.RolRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoCargoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoAreaRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoGrupoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoUsuarioRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.AutorizaRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.UsuParticipRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.ListaDescRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.OperacionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.UsuarioGrupoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.GrupoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.ConsModPagRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.PersonalRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.UsuarioPerRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LoadOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientTag {
            get {
                return this.ClientTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientTagField, value) != true)) {
                    this.ClientTagField = value;
                    this.RaisePropertyChanged("ClientTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LoadOptions {
            get {
                return this.LoadOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadOptionsField, value) != true)) {
                    this.LoadOptionsField = value;
                    this.RaisePropertyChanged("LoadOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class EmpresaRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eEmpresa CtrEmpresaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eEmpresa CtrEmpresa {
            get {
                return this.CtrEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrEmpresaField, value) != true)) {
                    this.CtrEmpresaField = value;
                    this.RaisePropertyChanged("CtrEmpresa");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccesoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class AccesoRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eAccesoSistema CtrAccesoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eAccesoSistema CtrAcceso {
            get {
                return this.CtrAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrAccesoField, value) != true)) {
                    this.CtrAccesoField = value;
                    this.RaisePropertyChanged("CtrAcceso");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAccesoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoAccesoRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoAcceso CtrTipoAccesoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoAcceso CtrTipoAcceso {
            get {
                return this.CtrTipoAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoAccesoField, value) != true)) {
                    this.CtrTipoAccesoField = value;
                    this.RaisePropertyChanged("CtrTipoAcceso");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPrioridadRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoPrioridadRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoPrioridad CtrTipoPrioridadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoPrioridad CtrTipoPrioridad {
            get {
                return this.CtrTipoPrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoPrioridadField, value) != true)) {
                    this.CtrTipoPrioridadField = value;
                    this.RaisePropertyChanged("CtrTipoPrioridad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoParticipRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoParticipRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoParticipacion CtrTipoParticField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoParticipacion CtrTipoPartic {
            get {
                return this.CtrTipoParticField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoParticField, value) != true)) {
                    this.CtrTipoParticField = value;
                    this.RaisePropertyChanged("CtrTipoPartic");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEventoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoEventoRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoEvento CtrTipoEventoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoEvento CtrTipoEvento {
            get {
                return this.CtrTipoEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoEventoField, value) != true)) {
                    this.CtrTipoEventoField = value;
                    this.RaisePropertyChanged("CtrTipoEvento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoOperacionRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoOperacionRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoOperacion CtrTipoOperField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoOperacion CtrTipoOper {
            get {
                return this.CtrTipoOperField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoOperField, value) != true)) {
                    this.CtrTipoOperField = value;
                    this.RaisePropertyChanged("CtrTipoOper");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class RolRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eRol CtrRolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eRol CtrRol {
            get {
                return this.CtrRolField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrRolField, value) != true)) {
                    this.CtrRolField = value;
                    this.RaisePropertyChanged("CtrRol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCargoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoCargoRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoCargo CtrTipoCargoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoCargo CtrTipoCargo {
            get {
                return this.CtrTipoCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoCargoField, value) != true)) {
                    this.CtrTipoCargoField = value;
                    this.RaisePropertyChanged("CtrTipoCargo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAreaRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoAreaRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eArea CtrTipoAreaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eArea CtrTipoArea {
            get {
                return this.CtrTipoAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoAreaField, value) != true)) {
                    this.CtrTipoAreaField = value;
                    this.RaisePropertyChanged("CtrTipoArea");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoGrupoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoGrupoRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eGrupo CtrTipoGrupoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eGrupo CtrTipoGrupo {
            get {
                return this.CtrTipoGrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoGrupoField, value) != true)) {
                    this.CtrTipoGrupoField = value;
                    this.RaisePropertyChanged("CtrTipoGrupo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUsuarioRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoUsuarioRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoUsuario CtrTipoUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoUsuario CtrTipoUsuario {
            get {
                return this.CtrTipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrTipoUsuarioField, value) != true)) {
                    this.CtrTipoUsuarioField = value;
                    this.RaisePropertyChanged("CtrTipoUsuario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorizaRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class AutorizaRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eAutorizador CtrAutorizaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eAutorizador CtrAutoriza {
            get {
                return this.CtrAutorizaField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrAutorizaField, value) != true)) {
                    this.CtrAutorizaField = value;
                    this.RaisePropertyChanged("CtrAutoriza");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuParticipRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class UsuParticipRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eParticipante CtrUsuPartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] ListCodiOperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] ListCodiUsuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eParticipante CtrUsuPart {
            get {
                return this.CtrUsuPartField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrUsuPartField, value) != true)) {
                    this.CtrUsuPartField = value;
                    this.RaisePropertyChanged("CtrUsuPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] ListCodiOper {
            get {
                return this.ListCodiOperField;
            }
            set {
                if ((object.ReferenceEquals(this.ListCodiOperField, value) != true)) {
                    this.ListCodiOperField = value;
                    this.RaisePropertyChanged("ListCodiOper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] ListCodiUsu {
            get {
                return this.ListCodiUsuField;
            }
            set {
                if ((object.ReferenceEquals(this.ListCodiUsuField, value) != true)) {
                    this.ListCodiUsuField = value;
                    this.RaisePropertyChanged("ListCodiUsu");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDescRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class ListaDescRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eVariable CtrDesListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eVariable CtrDesList {
            get {
                return this.CtrDesListField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrDesListField, value) != true)) {
                    this.CtrDesListField = value;
                    this.RaisePropertyChanged("CtrDesList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class OperacionRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eOperaciones CtrOperField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eOperaciones CtrOper {
            get {
                return this.CtrOperField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrOperField, value) != true)) {
                    this.CtrOperField = value;
                    this.RaisePropertyChanged("CtrOper");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioGrupoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class UsuarioGrupoRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eUsuarioGrupo CtrUsuarioGrupoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eUsuarioGrupo CtrUsuarioGrupo {
            get {
                return this.CtrUsuarioGrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrUsuarioGrupoField, value) != true)) {
                    this.CtrUsuarioGrupoField = value;
                    this.RaisePropertyChanged("CtrUsuarioGrupo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class GrupoRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eGrupo CtrGrupoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eGrupo CtrGrupo {
            get {
                return this.CtrGrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrGrupoField, value) != true)) {
                    this.CtrGrupoField = value;
                    this.RaisePropertyChanged("CtrGrupo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsModPagRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class ConsModPagRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eModuloPagina CtrModPagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eModuloPagina CtrModPag {
            get {
                return this.CtrModPagField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrModPagField, value) != true)) {
                    this.CtrModPagField = value;
                    this.RaisePropertyChanged("CtrModPag");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class PersonalRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.ePersonal CtrPersonalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.ePersonal CtrPersonal {
            get {
                return this.CtrPersonalField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrPersonalField, value) != true)) {
                    this.CtrPersonalField = value;
                    this.RaisePropertyChanged("CtrPersonal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioPerRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class UsuarioPerRequest : WebGdoc.GestionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eUsuario CtrUsuarioPerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eUsuario CtrUsuarioPer {
            get {
                return this.CtrUsuarioPerField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrUsuarioPerField, value) != true)) {
                    this.CtrUsuarioPerField = value;
                    this.RaisePropertyChanged("CtrUsuarioPer");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.LEmpresaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.LAccesoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoAccesoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoPrioridadResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.EmpresaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoParticipResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoEventoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoOperacionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.RolResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoCargoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoAreaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoGrupoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.TipoUsuarioResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.AutorizaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.UsuarioPerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.UsuParticipResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.LUserParticResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.ListaDescResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.OperacionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.UsuarioGrupoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.LUserAutoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.GrupoUsuarioResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.GrupoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.ConsModPagResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.AccesoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.PersonalResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.GestionServRef.UsuarioResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGdoc.GestionServRef.AcknowledgeType AcknowledgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationExpiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsAffectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGdoc.GestionServRef.AcknowledgeType Acknowledge {
            get {
                return this.AcknowledgeField;
            }
            set {
                if ((this.AcknowledgeField.Equals(value) != true)) {
                    this.AcknowledgeField = value;
                    this.RaisePropertyChanged("Acknowledge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Build {
            get {
                return this.BuildField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildField, value) != true)) {
                    this.BuildField = value;
                    this.RaisePropertyChanged("Build");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIdField, value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationExpires {
            get {
                return this.ReservationExpiresField;
            }
            set {
                if ((this.ReservationExpiresField.Equals(value) != true)) {
                    this.ReservationExpiresField = value;
                    this.RaisePropertyChanged("ReservationExpires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationId {
            get {
                return this.ReservationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationIdField, value) != true)) {
                    this.ReservationIdField = value;
                    this.RaisePropertyChanged("ReservationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsAffected {
            get {
                return this.RowsAffectedField;
            }
            set {
                if ((this.RowsAffectedField.Equals(value) != true)) {
                    this.RowsAffectedField = value;
                    this.RaisePropertyChanged("RowsAffected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LEmpresaResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LEmpresaResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eEmpresa[] EmpresaListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eEmpresa[] EmpresaLista {
            get {
                return this.EmpresaListaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaListaField, value) != true)) {
                    this.EmpresaListaField = value;
                    this.RaisePropertyChanged("EmpresaLista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LAccesoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LAccesoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eAccesoSistema[] ListaAccesoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eAccesoSistema[] ListaAcceso {
            get {
                return this.ListaAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaAccesoField, value) != true)) {
                    this.ListaAccesoField = value;
                    this.RaisePropertyChanged("ListaAcceso");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAccesoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoAccesoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoAcceso[] ListaTipoAccesoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoAcceso[] ListaTipoAcceso {
            get {
                return this.ListaTipoAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTipoAccesoField, value) != true)) {
                    this.ListaTipoAccesoField = value;
                    this.RaisePropertyChanged("ListaTipoAcceso");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPrioridadResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoPrioridadResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoPrioridad[] ListaTipoPrioridadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoPrioridad[] ListaTipoPrioridad {
            get {
                return this.ListaTipoPrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTipoPrioridadField, value) != true)) {
                    this.ListaTipoPrioridadField = value;
                    this.RaisePropertyChanged("ListaTipoPrioridad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class EmpresaResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddEmpresaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddEmpresa {
            get {
                return this.AddEmpresaField;
            }
            set {
                if ((this.AddEmpresaField.Equals(value) != true)) {
                    this.AddEmpresaField = value;
                    this.RaisePropertyChanged("AddEmpresa");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoParticipResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoParticipResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoParticipacion[] ListaParticipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoParticipacion[] ListaParticip {
            get {
                return this.ListaParticipField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaParticipField, value) != true)) {
                    this.ListaParticipField = value;
                    this.RaisePropertyChanged("ListaParticip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEventoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoEventoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoEvento[] ListaEventoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoEvento[] ListaEvento {
            get {
                return this.ListaEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaEventoField, value) != true)) {
                    this.ListaEventoField = value;
                    this.RaisePropertyChanged("ListaEvento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoOperacionResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoOperacionResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoOperacion[] ListOperacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoOperacion[] ListOperacion {
            get {
                return this.ListOperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ListOperacionField, value) != true)) {
                    this.ListOperacionField = value;
                    this.RaisePropertyChanged("ListOperacion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class RolResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eRol[] ListaRolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eRol[] ListaRol {
            get {
                return this.ListaRolField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaRolField, value) != true)) {
                    this.ListaRolField = value;
                    this.RaisePropertyChanged("ListaRol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCargoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoCargoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoCargo[] ListaTipoCargoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoCargo[] ListaTipoCargo {
            get {
                return this.ListaTipoCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTipoCargoField, value) != true)) {
                    this.ListaTipoCargoField = value;
                    this.RaisePropertyChanged("ListaTipoCargo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAreaResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoAreaResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eArea[] ListaTipoAreaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eArea[] ListaTipoArea {
            get {
                return this.ListaTipoAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTipoAreaField, value) != true)) {
                    this.ListaTipoAreaField = value;
                    this.RaisePropertyChanged("ListaTipoArea");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoGrupoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoGrupoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eGrupo[] ListaTipoGrupoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eGrupo[] ListaTipoGrupo {
            get {
                return this.ListaTipoGrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTipoGrupoField, value) != true)) {
                    this.ListaTipoGrupoField = value;
                    this.RaisePropertyChanged("ListaTipoGrupo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUsuarioResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class TipoUsuarioResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eTipoUsuario[] ListaTipoUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eTipoUsuario[] ListaTipoUsuario {
            get {
                return this.ListaTipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTipoUsuarioField, value) != true)) {
                    this.ListaTipoUsuarioField = value;
                    this.RaisePropertyChanged("ListaTipoUsuario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorizaResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class AutorizaResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddAutorizaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddAutoriza {
            get {
                return this.AddAutorizaField;
            }
            set {
                if ((this.AddAutorizaField.Equals(value) != true)) {
                    this.AddAutorizaField = value;
                    this.RaisePropertyChanged("AddAutoriza");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioPerResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class UsuarioPerResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eUsuario[] ListaUsuarioPerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eUsuario[] ListaUsuarioPer {
            get {
                return this.ListaUsuarioPerField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaUsuarioPerField, value) != true)) {
                    this.ListaUsuarioPerField = value;
                    this.RaisePropertyChanged("ListaUsuarioPer");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuParticipResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class UsuParticipResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddUsuPartipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UpdateUsuPartipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddUsuPartip {
            get {
                return this.AddUsuPartipField;
            }
            set {
                if ((this.AddUsuPartipField.Equals(value) != true)) {
                    this.AddUsuPartipField = value;
                    this.RaisePropertyChanged("AddUsuPartip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UpdateUsuPartip {
            get {
                return this.UpdateUsuPartipField;
            }
            set {
                if ((this.UpdateUsuPartipField.Equals(value) != true)) {
                    this.UpdateUsuPartipField = value;
                    this.RaisePropertyChanged("UpdateUsuPartip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LUserParticResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LUserParticResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eParticipante[] ListaUsuPartField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eParticipante[] ListaUsuPart {
            get {
                return this.ListaUsuPartField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaUsuPartField, value) != true)) {
                    this.ListaUsuPartField = value;
                    this.RaisePropertyChanged("ListaUsuPart");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDescResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class ListaDescResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eVariable[] ListDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eVariable[] ListDesc {
            get {
                return this.ListDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ListDescField, value) != true)) {
                    this.ListDescField = value;
                    this.RaisePropertyChanged("ListDesc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class OperacionResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eOperaciones[] OperacionListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eOperaciones[] OperacionLista {
            get {
                return this.OperacionListaField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionListaField, value) != true)) {
                    this.OperacionListaField = value;
                    this.RaisePropertyChanged("OperacionLista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioGrupoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class UsuarioGrupoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eUsuarioGrupo[] UsuarioGrupoListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eUsuarioGrupo[] UsuarioGrupoLista {
            get {
                return this.UsuarioGrupoListaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioGrupoListaField, value) != true)) {
                    this.UsuarioGrupoListaField = value;
                    this.RaisePropertyChanged("UsuarioGrupoLista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LUserAutoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LUserAutoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eAutorizador[] AutorizaListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eAutorizador[] AutorizaList {
            get {
                return this.AutorizaListField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizaListField, value) != true)) {
                    this.AutorizaListField = value;
                    this.RaisePropertyChanged("AutorizaList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupoUsuarioResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class GrupoUsuarioResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long GrupoUsuarioAddField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GrupoUsuarioAdd {
            get {
                return this.GrupoUsuarioAddField;
            }
            set {
                if ((this.GrupoUsuarioAddField.Equals(value) != true)) {
                    this.GrupoUsuarioAddField = value;
                    this.RaisePropertyChanged("GrupoUsuarioAdd");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class GrupoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddGrupoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddGrupo {
            get {
                return this.AddGrupoField;
            }
            set {
                if ((this.AddGrupoField.Equals(value) != true)) {
                    this.AddGrupoField = value;
                    this.RaisePropertyChanged("AddGrupo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsModPagResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class ConsModPagResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eModuloPagina[] ListaModPagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eModuloPagina[] ListaModPag {
            get {
                return this.ListaModPagField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaModPagField, value) != true)) {
                    this.ListaModPagField = value;
                    this.RaisePropertyChanged("ListaModPag");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccesoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class AccesoResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddAccesoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddAcceso {
            get {
                return this.AddAccesoField;
            }
            set {
                if ((this.AddAccesoField.Equals(value) != true)) {
                    this.AddAccesoField = value;
                    this.RaisePropertyChanged("AddAcceso");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class PersonalResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddPersonalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddPersonal {
            get {
                return this.AddPersonalField;
            }
            set {
                if ((this.AddPersonalField.Equals(value) != true)) {
                    this.AddPersonalField = value;
                    this.RaisePropertyChanged("AddPersonal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class UsuarioResponse : WebGdoc.GestionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddUser {
            get {
                return this.AddUserField;
            }
            set {
                if ((this.AddUserField.Equals(value) != true)) {
                    this.AddUserField = value;
                    this.RaisePropertyChanged("AddUser");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgeType", Namespace="http://www.yourcompany.com/types/")]
    public enum AcknowledgeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionServRef.IGestionService")]
    public interface IGestionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetAddUsuario", ReplyAction="http://tempuri.org/IGestionService/SetAddUsuarioResponse")]
        WebGdoc.GestionServRef.UsuarioResponse SetAddUsuario(WebGdoc.GestionServRef.UsuarioPerRequest RqtUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetUsuarioPer", ReplyAction="http://tempuri.org/IGestionService/SetUsuarioPerResponse")]
        WebGdoc.GestionServRef.UsuarioResponse SetUsuarioPer(WebGdoc.GestionServRef.UsuarioPerRequest RqtUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetEmpresa", ReplyAction="http://tempuri.org/IGestionService/GetEmpresaResponse")]
        WebGdoc.GestionServRef.LEmpresaResponse GetEmpresa(WebGdoc.GestionServRef.EmpresaRequest RqtEmpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetMenuUsuario", ReplyAction="http://tempuri.org/IGestionService/GetMenuUsuarioResponse")]
        WebGdoc.GestionServRef.LAccesoResponse GetMenuUsuario(WebGdoc.GestionServRef.AccesoRequest RqtMenu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetListaTipoAcceso", ReplyAction="http://tempuri.org/IGestionService/GetListaTipoAccesoResponse")]
        WebGdoc.GestionServRef.TipoAccesoResponse GetListaTipoAcceso(WebGdoc.GestionServRef.TipoAccesoRequest RqtListaTipoAcceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetListaTipoPrioridad", ReplyAction="http://tempuri.org/IGestionService/GetListaTipoPrioridadResponse")]
        WebGdoc.GestionServRef.TipoPrioridadResponse GetListaTipoPrioridad(WebGdoc.GestionServRef.TipoPrioridadRequest RqtListaTipoPrioridad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetEmpresaAdd", ReplyAction="http://tempuri.org/IGestionService/SetEmpresaAddResponse")]
        WebGdoc.GestionServRef.EmpresaResponse SetEmpresaAdd(WebGdoc.GestionServRef.EmpresaRequest RqtEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetListaTipoParticip", ReplyAction="http://tempuri.org/IGestionService/GetListaTipoParticipResponse")]
        WebGdoc.GestionServRef.TipoParticipResponse GetListaTipoParticip(WebGdoc.GestionServRef.TipoParticipRequest RqtListaTipoParticip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetTipoEvento", ReplyAction="http://tempuri.org/IGestionService/GetTipoEventoResponse")]
        WebGdoc.GestionServRef.TipoEventoResponse GetTipoEvento(WebGdoc.GestionServRef.TipoEventoRequest RqtTipoEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetTipoOperacion", ReplyAction="http://tempuri.org/IGestionService/GetTipoOperacionResponse")]
        WebGdoc.GestionServRef.TipoOperacionResponse GetTipoOperacion(WebGdoc.GestionServRef.TipoOperacionRequest RqtTipoOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetTipoRol", ReplyAction="http://tempuri.org/IGestionService/GetTipoRolResponse")]
        WebGdoc.GestionServRef.RolResponse GetTipoRol(WebGdoc.GestionServRef.RolRequest RqtRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetTipoCargo", ReplyAction="http://tempuri.org/IGestionService/GetTipoCargoResponse")]
        WebGdoc.GestionServRef.TipoCargoResponse GetTipoCargo(WebGdoc.GestionServRef.TipoCargoRequest RqtTipocargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetTipoArea", ReplyAction="http://tempuri.org/IGestionService/GetTipoAreaResponse")]
        WebGdoc.GestionServRef.TipoAreaResponse GetTipoArea(WebGdoc.GestionServRef.TipoAreaRequest RqtTipoArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetTipoGrupo", ReplyAction="http://tempuri.org/IGestionService/GetTipoGrupoResponse")]
        WebGdoc.GestionServRef.TipoGrupoResponse GetTipoGrupo(WebGdoc.GestionServRef.TipoGrupoRequest RqtTipoGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetTipoUsuario", ReplyAction="http://tempuri.org/IGestionService/GetTipoUsuarioResponse")]
        WebGdoc.GestionServRef.TipoUsuarioResponse GetTipoUsuario(WebGdoc.GestionServRef.TipoUsuarioRequest RqtTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetTipoUsuGrupo", ReplyAction="http://tempuri.org/IGestionService/GetTipoUsuGrupoResponse")]
        WebGdoc.GestionServRef.TipoGrupoResponse GetTipoUsuGrupo(WebGdoc.GestionServRef.TipoGrupoRequest RqtTipoUsuGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetAutorizaAdd", ReplyAction="http://tempuri.org/IGestionService/SetAutorizaAddResponse")]
        WebGdoc.GestionServRef.AutorizaResponse SetAutorizaAdd(WebGdoc.GestionServRef.AutorizaRequest RqtAutoriza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetListaUsuarioPer", ReplyAction="http://tempuri.org/IGestionService/GetListaUsuarioPerResponse")]
        WebGdoc.GestionServRef.UsuarioPerResponse GetListaUsuarioPer(WebGdoc.GestionServRef.UsuarioPerRequest RqtUsuarioPerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetListaUsuarioGrupo", ReplyAction="http://tempuri.org/IGestionService/GetListaUsuarioGrupoResponse")]
        WebGdoc.GestionServRef.UsuarioPerResponse GetListaUsuarioGrupo(WebGdoc.GestionServRef.UsuarioPerRequest RqtListaUsuarioPer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetUsuParticipante", ReplyAction="http://tempuri.org/IGestionService/SetUsuParticipanteResponse")]
        WebGdoc.GestionServRef.UsuParticipResponse SetUsuParticipante(WebGdoc.GestionServRef.UsuParticipRequest RqtUsuParticipRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/UpdateUsuParticipante", ReplyAction="http://tempuri.org/IGestionService/UpdateUsuParticipanteResponse")]
        WebGdoc.GestionServRef.UsuParticipResponse UpdateUsuParticipante(WebGdoc.GestionServRef.UsuParticipRequest RqtUsuParticip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetUserPart", ReplyAction="http://tempuri.org/IGestionService/GetUserPartResponse")]
        WebGdoc.GestionServRef.LUserParticResponse GetUserPart(WebGdoc.GestionServRef.UsuParticipRequest RqtUserPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetUserPartBatch", ReplyAction="http://tempuri.org/IGestionService/GetUserPartBatchResponse")]
        WebGdoc.GestionServRef.LUserParticResponse GetUserPartBatch(WebGdoc.GestionServRef.UsuParticipRequest RqtUserPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetAnulaUserPart", ReplyAction="http://tempuri.org/IGestionService/SetAnulaUserPartResponse")]
        WebGdoc.GestionServRef.UsuParticipResponse SetAnulaUserPart(WebGdoc.GestionServRef.UsuParticipRequest RqtAnulaUserP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetListDes", ReplyAction="http://tempuri.org/IGestionService/GetListDesResponse")]
        WebGdoc.GestionServRef.ListaDescResponse GetListDes(WebGdoc.GestionServRef.ListaDescRequest RqtListaDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetListOper", ReplyAction="http://tempuri.org/IGestionService/GetListOperResponse")]
        WebGdoc.GestionServRef.OperacionResponse GetListOper(WebGdoc.GestionServRef.OperacionRequest RqtListOper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetUsuarioGrupo", ReplyAction="http://tempuri.org/IGestionService/GetUsuarioGrupoResponse")]
        WebGdoc.GestionServRef.UsuarioGrupoResponse GetUsuarioGrupo(WebGdoc.GestionServRef.UsuarioGrupoRequest RqtUsuarioGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetAutorizaList", ReplyAction="http://tempuri.org/IGestionService/GetAutorizaListResponse")]
        WebGdoc.GestionServRef.LUserAutoResponse GetAutorizaList(WebGdoc.GestionServRef.AutorizaRequest RqtAutoriza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetGrupoUser", ReplyAction="http://tempuri.org/IGestionService/SetGrupoUserResponse")]
        WebGdoc.GestionServRef.GrupoUsuarioResponse SetGrupoUser(WebGdoc.GestionServRef.UsuarioGrupoRequest RqtGrupoUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetGrupoAdd", ReplyAction="http://tempuri.org/IGestionService/SetGrupoAddResponse")]
        WebGdoc.GestionServRef.GrupoResponse SetGrupoAdd(ref WebGdoc.GestionServRef.GrupoRequest RqtGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetAnulaGrupoUser", ReplyAction="http://tempuri.org/IGestionService/SetAnulaGrupoUserResponse")]
        WebGdoc.GestionServRef.GrupoUsuarioResponse SetAnulaGrupoUser(WebGdoc.GestionServRef.UsuarioGrupoRequest RqtGrupoUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetModuloPagina", ReplyAction="http://tempuri.org/IGestionService/GetModuloPaginaResponse")]
        WebGdoc.GestionServRef.ConsModPagResponse GetModuloPagina(WebGdoc.GestionServRef.ConsModPagRequest RqtModPag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetAccesoSistema", ReplyAction="http://tempuri.org/IGestionService/SetAccesoSistemaResponse")]
        WebGdoc.GestionServRef.AccesoResponse SetAccesoSistema(WebGdoc.GestionServRef.AccesoRequest RqtAcceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/GetAccesoSistema", ReplyAction="http://tempuri.org/IGestionService/GetAccesoSistemaResponse")]
        WebGdoc.GestionServRef.LAccesoResponse GetAccesoSistema(WebGdoc.GestionServRef.AccesoRequest RqtAccesolist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetAnulaAcceso", ReplyAction="http://tempuri.org/IGestionService/SetAnulaAccesoResponse")]
        WebGdoc.GestionServRef.AccesoResponse SetAnulaAcceso(WebGdoc.GestionServRef.AccesoRequest RqtAcceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionService/SetAddPersonal", ReplyAction="http://tempuri.org/IGestionService/SetAddPersonalResponse")]
        WebGdoc.GestionServRef.PersonalResponse SetAddPersonal(ref WebGdoc.GestionServRef.PersonalRequest RqtPersonal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionServiceChannel : WebGdoc.GestionServRef.IGestionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionServiceClient : System.ServiceModel.ClientBase<WebGdoc.GestionServRef.IGestionService>, WebGdoc.GestionServRef.IGestionService {
        
        public GestionServiceClient() {
        }
        
        public GestionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebGdoc.GestionServRef.UsuarioResponse SetAddUsuario(WebGdoc.GestionServRef.UsuarioPerRequest RqtUser) {
            return base.Channel.SetAddUsuario(RqtUser);
        }
        
        public WebGdoc.GestionServRef.UsuarioResponse SetUsuarioPer(WebGdoc.GestionServRef.UsuarioPerRequest RqtUser) {
            return base.Channel.SetUsuarioPer(RqtUser);
        }
        
        public WebGdoc.GestionServRef.LEmpresaResponse GetEmpresa(WebGdoc.GestionServRef.EmpresaRequest RqtEmpr) {
            return base.Channel.GetEmpresa(RqtEmpr);
        }
        
        public WebGdoc.GestionServRef.LAccesoResponse GetMenuUsuario(WebGdoc.GestionServRef.AccesoRequest RqtMenu) {
            return base.Channel.GetMenuUsuario(RqtMenu);
        }
        
        public WebGdoc.GestionServRef.TipoAccesoResponse GetListaTipoAcceso(WebGdoc.GestionServRef.TipoAccesoRequest RqtListaTipoAcceso) {
            return base.Channel.GetListaTipoAcceso(RqtListaTipoAcceso);
        }
        
        public WebGdoc.GestionServRef.TipoPrioridadResponse GetListaTipoPrioridad(WebGdoc.GestionServRef.TipoPrioridadRequest RqtListaTipoPrioridad) {
            return base.Channel.GetListaTipoPrioridad(RqtListaTipoPrioridad);
        }
        
        public WebGdoc.GestionServRef.EmpresaResponse SetEmpresaAdd(WebGdoc.GestionServRef.EmpresaRequest RqtEmpresa) {
            return base.Channel.SetEmpresaAdd(RqtEmpresa);
        }
        
        public WebGdoc.GestionServRef.TipoParticipResponse GetListaTipoParticip(WebGdoc.GestionServRef.TipoParticipRequest RqtListaTipoParticip) {
            return base.Channel.GetListaTipoParticip(RqtListaTipoParticip);
        }
        
        public WebGdoc.GestionServRef.TipoEventoResponse GetTipoEvento(WebGdoc.GestionServRef.TipoEventoRequest RqtTipoEvento) {
            return base.Channel.GetTipoEvento(RqtTipoEvento);
        }
        
        public WebGdoc.GestionServRef.TipoOperacionResponse GetTipoOperacion(WebGdoc.GestionServRef.TipoOperacionRequest RqtTipoOperacion) {
            return base.Channel.GetTipoOperacion(RqtTipoOperacion);
        }
        
        public WebGdoc.GestionServRef.RolResponse GetTipoRol(WebGdoc.GestionServRef.RolRequest RqtRol) {
            return base.Channel.GetTipoRol(RqtRol);
        }
        
        public WebGdoc.GestionServRef.TipoCargoResponse GetTipoCargo(WebGdoc.GestionServRef.TipoCargoRequest RqtTipocargo) {
            return base.Channel.GetTipoCargo(RqtTipocargo);
        }
        
        public WebGdoc.GestionServRef.TipoAreaResponse GetTipoArea(WebGdoc.GestionServRef.TipoAreaRequest RqtTipoArea) {
            return base.Channel.GetTipoArea(RqtTipoArea);
        }
        
        public WebGdoc.GestionServRef.TipoGrupoResponse GetTipoGrupo(WebGdoc.GestionServRef.TipoGrupoRequest RqtTipoGrupo) {
            return base.Channel.GetTipoGrupo(RqtTipoGrupo);
        }
        
        public WebGdoc.GestionServRef.TipoUsuarioResponse GetTipoUsuario(WebGdoc.GestionServRef.TipoUsuarioRequest RqtTipoUsuario) {
            return base.Channel.GetTipoUsuario(RqtTipoUsuario);
        }
        
        public WebGdoc.GestionServRef.TipoGrupoResponse GetTipoUsuGrupo(WebGdoc.GestionServRef.TipoGrupoRequest RqtTipoUsuGrupo) {
            return base.Channel.GetTipoUsuGrupo(RqtTipoUsuGrupo);
        }
        
        public WebGdoc.GestionServRef.AutorizaResponse SetAutorizaAdd(WebGdoc.GestionServRef.AutorizaRequest RqtAutoriza) {
            return base.Channel.SetAutorizaAdd(RqtAutoriza);
        }
        
        public WebGdoc.GestionServRef.UsuarioPerResponse GetListaUsuarioPer(WebGdoc.GestionServRef.UsuarioPerRequest RqtUsuarioPerRequest) {
            return base.Channel.GetListaUsuarioPer(RqtUsuarioPerRequest);
        }
        
        public WebGdoc.GestionServRef.UsuarioPerResponse GetListaUsuarioGrupo(WebGdoc.GestionServRef.UsuarioPerRequest RqtListaUsuarioPer) {
            return base.Channel.GetListaUsuarioGrupo(RqtListaUsuarioPer);
        }
        
        public WebGdoc.GestionServRef.UsuParticipResponse SetUsuParticipante(WebGdoc.GestionServRef.UsuParticipRequest RqtUsuParticipRequest) {
            return base.Channel.SetUsuParticipante(RqtUsuParticipRequest);
        }
        
        public WebGdoc.GestionServRef.UsuParticipResponse UpdateUsuParticipante(WebGdoc.GestionServRef.UsuParticipRequest RqtUsuParticip) {
            return base.Channel.UpdateUsuParticipante(RqtUsuParticip);
        }
        
        public WebGdoc.GestionServRef.LUserParticResponse GetUserPart(WebGdoc.GestionServRef.UsuParticipRequest RqtUserPart) {
            return base.Channel.GetUserPart(RqtUserPart);
        }
        
        public WebGdoc.GestionServRef.LUserParticResponse GetUserPartBatch(WebGdoc.GestionServRef.UsuParticipRequest RqtUserPart) {
            return base.Channel.GetUserPartBatch(RqtUserPart);
        }
        
        public WebGdoc.GestionServRef.UsuParticipResponse SetAnulaUserPart(WebGdoc.GestionServRef.UsuParticipRequest RqtAnulaUserP) {
            return base.Channel.SetAnulaUserPart(RqtAnulaUserP);
        }
        
        public WebGdoc.GestionServRef.ListaDescResponse GetListDes(WebGdoc.GestionServRef.ListaDescRequest RqtListaDesc) {
            return base.Channel.GetListDes(RqtListaDesc);
        }
        
        public WebGdoc.GestionServRef.OperacionResponse GetListOper(WebGdoc.GestionServRef.OperacionRequest RqtListOper) {
            return base.Channel.GetListOper(RqtListOper);
        }
        
        public WebGdoc.GestionServRef.UsuarioGrupoResponse GetUsuarioGrupo(WebGdoc.GestionServRef.UsuarioGrupoRequest RqtUsuarioGrupo) {
            return base.Channel.GetUsuarioGrupo(RqtUsuarioGrupo);
        }
        
        public WebGdoc.GestionServRef.LUserAutoResponse GetAutorizaList(WebGdoc.GestionServRef.AutorizaRequest RqtAutoriza) {
            return base.Channel.GetAutorizaList(RqtAutoriza);
        }
        
        public WebGdoc.GestionServRef.GrupoUsuarioResponse SetGrupoUser(WebGdoc.GestionServRef.UsuarioGrupoRequest RqtGrupoUser) {
            return base.Channel.SetGrupoUser(RqtGrupoUser);
        }
        
        public WebGdoc.GestionServRef.GrupoResponse SetGrupoAdd(ref WebGdoc.GestionServRef.GrupoRequest RqtGrupo) {
            return base.Channel.SetGrupoAdd(ref RqtGrupo);
        }
        
        public WebGdoc.GestionServRef.GrupoUsuarioResponse SetAnulaGrupoUser(WebGdoc.GestionServRef.UsuarioGrupoRequest RqtGrupoUser) {
            return base.Channel.SetAnulaGrupoUser(RqtGrupoUser);
        }
        
        public WebGdoc.GestionServRef.ConsModPagResponse GetModuloPagina(WebGdoc.GestionServRef.ConsModPagRequest RqtModPag) {
            return base.Channel.GetModuloPagina(RqtModPag);
        }
        
        public WebGdoc.GestionServRef.AccesoResponse SetAccesoSistema(WebGdoc.GestionServRef.AccesoRequest RqtAcceso) {
            return base.Channel.SetAccesoSistema(RqtAcceso);
        }
        
        public WebGdoc.GestionServRef.LAccesoResponse GetAccesoSistema(WebGdoc.GestionServRef.AccesoRequest RqtAccesolist) {
            return base.Channel.GetAccesoSistema(RqtAccesolist);
        }
        
        public WebGdoc.GestionServRef.AccesoResponse SetAnulaAcceso(WebGdoc.GestionServRef.AccesoRequest RqtAcceso) {
            return base.Channel.SetAnulaAcceso(RqtAcceso);
        }
        
        public WebGdoc.GestionServRef.PersonalResponse SetAddPersonal(ref WebGdoc.GestionServRef.PersonalRequest RqtPersonal) {
            return base.Channel.SetAddPersonal(ref RqtPersonal);
        }
    }
}
