//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGdoc.DigitalizacionServRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocDigRefRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocDigDTRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocAdjRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocumentoElectronicoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.LogOperacionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.MensajeAlertaRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.MesaVirtualRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocDigRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LoadOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientTag {
            get {
                return this.ClientTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientTagField, value) != true)) {
                    this.ClientTagField = value;
                    this.RaisePropertyChanged("ClientTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LoadOptions {
            get {
                return this.LoadOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadOptionsField, value) != true)) {
                    this.LoadOptionsField = value;
                    this.RaisePropertyChanged("LoadOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocDigRefRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocDigRefRequest : WebGdoc.DigitalizacionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocDigRef CtrDocDigRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocDigRef CtrDocDigRef {
            get {
                return this.CtrDocDigRefField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrDocDigRefField, value) != true)) {
                    this.CtrDocDigRefField = value;
                    this.RaisePropertyChanged("CtrDocDigRef");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocDigDTRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocDigDTRequest : WebGdoc.DigitalizacionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocDigListTD CtrDocDigTDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocDigListTD CtrDocDigTD {
            get {
                return this.CtrDocDigTDField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrDocDigTDField, value) != true)) {
                    this.CtrDocDigTDField = value;
                    this.RaisePropertyChanged("CtrDocDigTD");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocAdjRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocAdjRequest : WebGdoc.DigitalizacionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocAdj CtrDocAdjField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocAdj CtrDocAdj {
            get {
                return this.CtrDocAdjField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrDocAdjField, value) != true)) {
                    this.CtrDocAdjField = value;
                    this.RaisePropertyChanged("CtrDocAdj");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoElectronicoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocumentoElectronicoRequest : WebGdoc.DigitalizacionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocumentoElectronico CtrDocumentoElectronicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocumentoElectronico CtrDocumentoElectronico {
            get {
                return this.CtrDocumentoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrDocumentoElectronicoField, value) != true)) {
                    this.CtrDocumentoElectronicoField = value;
                    this.RaisePropertyChanged("CtrDocumentoElectronico");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogOperacionRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LogOperacionRequest : WebGdoc.DigitalizacionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eLogOperacion CtrLogOperField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eLogOperacion CtrLogOper {
            get {
                return this.CtrLogOperField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrLogOperField, value) != true)) {
                    this.CtrLogOperField = value;
                    this.RaisePropertyChanged("CtrLogOper");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajeAlertaRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class MensajeAlertaRequest : WebGdoc.DigitalizacionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eMensajeAlerta CtrMenAlertField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eMensajeAlerta CtrMenAlert {
            get {
                return this.CtrMenAlertField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrMenAlertField, value) != true)) {
                    this.CtrMenAlertField = value;
                    this.RaisePropertyChanged("CtrMenAlert");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MesaVirtualRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class MesaVirtualRequest : WebGdoc.DigitalizacionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eMesaVirtual CtrMesaVirField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eMesaVirtual CtrMesaVir {
            get {
                return this.CtrMesaVirField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrMesaVirField, value) != true)) {
                    this.CtrMesaVirField = value;
                    this.RaisePropertyChanged("CtrMesaVir");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocDigRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocDigRequest : WebGdoc.DigitalizacionServRef.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocDig CtrDocDigField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocDig CtrDocDig {
            get {
                return this.CtrDocDigField;
            }
            set {
                if ((object.ReferenceEquals(this.CtrDocDigField, value) != true)) {
                    this.CtrDocDigField = value;
                    this.RaisePropertyChanged("CtrDocDig");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.LDocDigResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocDigRefResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.LDocDigRefResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocDigDTResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocAdjResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.LDocAdjResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocumentoElectronicoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.LDocElecResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.LogOperacionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.MensajeAlertaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.LMensajeAlertaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.MesaVirtualResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.InsertMesaVResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebGdoc.DigitalizacionServRef.DocDigResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGdoc.DigitalizacionServRef.AcknowledgeType AcknowledgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationExpiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsAffectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGdoc.DigitalizacionServRef.AcknowledgeType Acknowledge {
            get {
                return this.AcknowledgeField;
            }
            set {
                if ((this.AcknowledgeField.Equals(value) != true)) {
                    this.AcknowledgeField = value;
                    this.RaisePropertyChanged("Acknowledge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Build {
            get {
                return this.BuildField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildField, value) != true)) {
                    this.BuildField = value;
                    this.RaisePropertyChanged("Build");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIdField, value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationExpires {
            get {
                return this.ReservationExpiresField;
            }
            set {
                if ((this.ReservationExpiresField.Equals(value) != true)) {
                    this.ReservationExpiresField = value;
                    this.RaisePropertyChanged("ReservationExpires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationId {
            get {
                return this.ReservationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationIdField, value) != true)) {
                    this.ReservationIdField = value;
                    this.RaisePropertyChanged("ReservationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsAffected {
            get {
                return this.RowsAffectedField;
            }
            set {
                if ((this.RowsAffectedField.Equals(value) != true)) {
                    this.RowsAffectedField = value;
                    this.RaisePropertyChanged("RowsAffected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LDocDigResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LDocDigResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocDig[] ListaDocDigField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocDig[] ListaDocDig {
            get {
                return this.ListaDocDigField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaDocDigField, value) != true)) {
                    this.ListaDocDigField = value;
                    this.RaisePropertyChanged("ListaDocDig");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocDigRefResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocDigRefResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddDocDigRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddDocDigRef {
            get {
                return this.AddDocDigRefField;
            }
            set {
                if ((this.AddDocDigRefField.Equals(value) != true)) {
                    this.AddDocDigRefField = value;
                    this.RaisePropertyChanged("AddDocDigRef");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LDocDigRefResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LDocDigRefResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocDigRef[] ListaRefDigitalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocDigRef[] ListaRefDigital {
            get {
                return this.ListaRefDigitalField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaRefDigitalField, value) != true)) {
                    this.ListaRefDigitalField = value;
                    this.RaisePropertyChanged("ListaRefDigital");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocDigDTResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocDigDTResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocDigListTD[] ListaDogDigField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocDigListTD[] ListaDogDig {
            get {
                return this.ListaDogDigField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaDogDigField, value) != true)) {
                    this.ListaDogDigField = value;
                    this.RaisePropertyChanged("ListaDogDig");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocAdjResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocAdjResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddDocAdjField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddDocAdj {
            get {
                return this.AddDocAdjField;
            }
            set {
                if ((this.AddDocAdjField.Equals(value) != true)) {
                    this.AddDocAdjField = value;
                    this.RaisePropertyChanged("AddDocAdj");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LDocAdjResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LDocAdjResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocAdj[] ListAdjField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocAdj[] ListAdj {
            get {
                return this.ListAdjField;
            }
            set {
                if ((object.ReferenceEquals(this.ListAdjField, value) != true)) {
                    this.ListAdjField = value;
                    this.RaisePropertyChanged("ListAdj");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoElectronicoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocumentoElectronicoResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EnviarDocumentoElectronicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EnviarDocumentoElectronico {
            get {
                return this.EnviarDocumentoElectronicoField;
            }
            set {
                if ((this.EnviarDocumentoElectronicoField.Equals(value) != true)) {
                    this.EnviarDocumentoElectronicoField = value;
                    this.RaisePropertyChanged("EnviarDocumentoElectronico");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LDocElecResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LDocElecResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eDocumentoElectronico[] ListaDocElecttonicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eDocumentoElectronico[] ListaDocElecttonico {
            get {
                return this.ListaDocElecttonicoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaDocElecttonicoField, value) != true)) {
                    this.ListaDocElecttonicoField = value;
                    this.RaisePropertyChanged("ListaDocElecttonico");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogOperacionResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LogOperacionResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddLogOperacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddLogOperacion {
            get {
                return this.AddLogOperacionField;
            }
            set {
                if ((this.AddLogOperacionField.Equals(value) != true)) {
                    this.AddLogOperacionField = value;
                    this.RaisePropertyChanged("AddLogOperacion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajeAlertaResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class MensajeAlertaResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddMensajeAlertaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddMensajeAlerta {
            get {
                return this.AddMensajeAlertaField;
            }
            set {
                if ((this.AddMensajeAlertaField.Equals(value) != true)) {
                    this.AddMensajeAlertaField = value;
                    this.RaisePropertyChanged("AddMensajeAlerta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LMensajeAlertaResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class LMensajeAlertaResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eMensajeAlerta[] ListaAlertaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eMensajeAlerta[] ListaAlerta {
            get {
                return this.ListaAlertaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaAlertaField, value) != true)) {
                    this.ListaAlertaField = value;
                    this.RaisePropertyChanged("ListaAlerta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MesaVirtualResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class MesaVirtualResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entity.Entities.eMesaVirtual[] ListaMesaVirtualField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entity.Entities.eMesaVirtual[] ListaMesaVirtual {
            get {
                return this.ListaMesaVirtualField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaMesaVirtualField, value) != true)) {
                    this.ListaMesaVirtualField = value;
                    this.RaisePropertyChanged("ListaMesaVirtual");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertMesaVResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class InsertMesaVResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long addMesaVirtualField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long addMesaVirtual {
            get {
                return this.addMesaVirtualField;
            }
            set {
                if ((this.addMesaVirtualField.Equals(value) != true)) {
                    this.addMesaVirtualField = value;
                    this.RaisePropertyChanged("addMesaVirtual");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocDigResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class DocDigResponse : WebGdoc.DigitalizacionServRef.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddDocDigField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddDocDig {
            get {
                return this.AddDocDigField;
            }
            set {
                if ((this.AddDocDigField.Equals(value) != true)) {
                    this.AddDocDigField = value;
                    this.RaisePropertyChanged("AddDocDig");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgeType", Namespace="http://www.yourcompany.com/types/")]
    public enum AcknowledgeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DigitalizacionServRef.IDigitalizacionService")]
    public interface IDigitalizacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetDocDigAdd", ReplyAction="http://tempuri.org/IDigitalizacionService/SetDocDigAddResponse")]
        WebGdoc.DigitalizacionServRef.DocDigResponse SetDocDigAdd(ref WebGdoc.DigitalizacionServRef.DocDigRequest RqtDocDig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/GetDocDigital", ReplyAction="http://tempuri.org/IDigitalizacionService/GetDocDigitalResponse")]
        WebGdoc.DigitalizacionServRef.LDocDigResponse GetDocDigital(WebGdoc.DigitalizacionServRef.DocDigRequest RqtDocDigi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetDocDigRefAdd", ReplyAction="http://tempuri.org/IDigitalizacionService/SetDocDigRefAddResponse")]
        WebGdoc.DigitalizacionServRef.DocDigRefResponse SetDocDigRefAdd(WebGdoc.DigitalizacionServRef.DocDigRefRequest RqtDocDigRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/GetDocDigRef", ReplyAction="http://tempuri.org/IDigitalizacionService/GetDocDigRefResponse")]
        WebGdoc.DigitalizacionServRef.LDocDigRefResponse GetDocDigRef(WebGdoc.DigitalizacionServRef.DocDigRefRequest RqtDocDigRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/GetListaTipoDoc", ReplyAction="http://tempuri.org/IDigitalizacionService/GetListaTipoDocResponse")]
        WebGdoc.DigitalizacionServRef.DocDigDTResponse GetListaTipoDoc(WebGdoc.DigitalizacionServRef.DocDigDTRequest RqtListaTipoDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetDocAdj", ReplyAction="http://tempuri.org/IDigitalizacionService/SetDocAdjResponse")]
        WebGdoc.DigitalizacionServRef.DocAdjResponse SetDocAdj(WebGdoc.DigitalizacionServRef.DocAdjRequest RqtDocAdj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/GetDocAdj", ReplyAction="http://tempuri.org/IDigitalizacionService/GetDocAdjResponse")]
        WebGdoc.DigitalizacionServRef.LDocAdjResponse GetDocAdj(WebGdoc.DigitalizacionServRef.DocAdjRequest RqtDocAdj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetAnulaDocAdj", ReplyAction="http://tempuri.org/IDigitalizacionService/SetAnulaDocAdjResponse")]
        WebGdoc.DigitalizacionServRef.DocAdjResponse SetAnulaDocAdj(WebGdoc.DigitalizacionServRef.DocAdjRequest RqtDocAdj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetDocumentoElectronicoEnviar", ReplyAction="http://tempuri.org/IDigitalizacionService/SetDocumentoElectronicoEnviarResponse")]
        WebGdoc.DigitalizacionServRef.DocumentoElectronicoResponse SetDocumentoElectronicoEnviar(ref WebGdoc.DigitalizacionServRef.DocumentoElectronicoRequest RqtDocumentoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/GetDocElec", ReplyAction="http://tempuri.org/IDigitalizacionService/GetDocElecResponse")]
        WebGdoc.DigitalizacionServRef.LDocElecResponse GetDocElec(WebGdoc.DigitalizacionServRef.DocumentoElectronicoRequest RqtDocElect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetLogOperacion", ReplyAction="http://tempuri.org/IDigitalizacionService/SetLogOperacionResponse")]
        WebGdoc.DigitalizacionServRef.LogOperacionResponse SetLogOperacion(WebGdoc.DigitalizacionServRef.LogOperacionRequest RqtLogOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetMensajeAlerta", ReplyAction="http://tempuri.org/IDigitalizacionService/SetMensajeAlertaResponse")]
        WebGdoc.DigitalizacionServRef.MensajeAlertaResponse SetMensajeAlerta(WebGdoc.DigitalizacionServRef.MensajeAlertaRequest RqtMensajeAlerta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/GetMensajAlerta", ReplyAction="http://tempuri.org/IDigitalizacionService/GetMensajAlertaResponse")]
        WebGdoc.DigitalizacionServRef.LMensajeAlertaResponse GetMensajAlerta(WebGdoc.DigitalizacionServRef.MensajeAlertaRequest RqtMensAlert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/GetListMesaVirtual", ReplyAction="http://tempuri.org/IDigitalizacionService/GetListMesaVirtualResponse")]
        WebGdoc.DigitalizacionServRef.MesaVirtualResponse GetListMesaVirtual(WebGdoc.DigitalizacionServRef.MesaVirtualRequest RqtListMesVir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetMesaVirtual", ReplyAction="http://tempuri.org/IDigitalizacionService/SetMesaVirtualResponse")]
        WebGdoc.DigitalizacionServRef.InsertMesaVResponse SetMesaVirtual(ref WebGdoc.DigitalizacionServRef.MesaVirtualRequest RqtListMesVir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/SetMesaComent", ReplyAction="http://tempuri.org/IDigitalizacionService/SetMesaComentResponse")]
        WebGdoc.DigitalizacionServRef.InsertMesaVResponse SetMesaComent(ref WebGdoc.DigitalizacionServRef.MesaVirtualRequest RqtComentVir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalizacionService/GetListMesaComent", ReplyAction="http://tempuri.org/IDigitalizacionService/GetListMesaComentResponse")]
        WebGdoc.DigitalizacionServRef.MesaVirtualResponse GetListMesaComent(WebGdoc.DigitalizacionServRef.MesaVirtualRequest RqtListMesCom);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDigitalizacionServiceChannel : WebGdoc.DigitalizacionServRef.IDigitalizacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DigitalizacionServiceClient : System.ServiceModel.ClientBase<WebGdoc.DigitalizacionServRef.IDigitalizacionService>, WebGdoc.DigitalizacionServRef.IDigitalizacionService {
        
        public DigitalizacionServiceClient() {
        }
        
        public DigitalizacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DigitalizacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalizacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalizacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebGdoc.DigitalizacionServRef.DocDigResponse SetDocDigAdd(ref WebGdoc.DigitalizacionServRef.DocDigRequest RqtDocDig) {
            return base.Channel.SetDocDigAdd(ref RqtDocDig);
        }
        
        public WebGdoc.DigitalizacionServRef.LDocDigResponse GetDocDigital(WebGdoc.DigitalizacionServRef.DocDigRequest RqtDocDigi) {
            return base.Channel.GetDocDigital(RqtDocDigi);
        }
        
        public WebGdoc.DigitalizacionServRef.DocDigRefResponse SetDocDigRefAdd(WebGdoc.DigitalizacionServRef.DocDigRefRequest RqtDocDigRef) {
            return base.Channel.SetDocDigRefAdd(RqtDocDigRef);
        }
        
        public WebGdoc.DigitalizacionServRef.LDocDigRefResponse GetDocDigRef(WebGdoc.DigitalizacionServRef.DocDigRefRequest RqtDocDigRef) {
            return base.Channel.GetDocDigRef(RqtDocDigRef);
        }
        
        public WebGdoc.DigitalizacionServRef.DocDigDTResponse GetListaTipoDoc(WebGdoc.DigitalizacionServRef.DocDigDTRequest RqtListaTipoDoc) {
            return base.Channel.GetListaTipoDoc(RqtListaTipoDoc);
        }
        
        public WebGdoc.DigitalizacionServRef.DocAdjResponse SetDocAdj(WebGdoc.DigitalizacionServRef.DocAdjRequest RqtDocAdj) {
            return base.Channel.SetDocAdj(RqtDocAdj);
        }
        
        public WebGdoc.DigitalizacionServRef.LDocAdjResponse GetDocAdj(WebGdoc.DigitalizacionServRef.DocAdjRequest RqtDocAdj) {
            return base.Channel.GetDocAdj(RqtDocAdj);
        }
        
        public WebGdoc.DigitalizacionServRef.DocAdjResponse SetAnulaDocAdj(WebGdoc.DigitalizacionServRef.DocAdjRequest RqtDocAdj) {
            return base.Channel.SetAnulaDocAdj(RqtDocAdj);
        }
        
        public WebGdoc.DigitalizacionServRef.DocumentoElectronicoResponse SetDocumentoElectronicoEnviar(ref WebGdoc.DigitalizacionServRef.DocumentoElectronicoRequest RqtDocumentoElectronico) {
            return base.Channel.SetDocumentoElectronicoEnviar(ref RqtDocumentoElectronico);
        }
        
        public WebGdoc.DigitalizacionServRef.LDocElecResponse GetDocElec(WebGdoc.DigitalizacionServRef.DocumentoElectronicoRequest RqtDocElect) {
            return base.Channel.GetDocElec(RqtDocElect);
        }
        
        public WebGdoc.DigitalizacionServRef.LogOperacionResponse SetLogOperacion(WebGdoc.DigitalizacionServRef.LogOperacionRequest RqtLogOperacion) {
            return base.Channel.SetLogOperacion(RqtLogOperacion);
        }
        
        public WebGdoc.DigitalizacionServRef.MensajeAlertaResponse SetMensajeAlerta(WebGdoc.DigitalizacionServRef.MensajeAlertaRequest RqtMensajeAlerta) {
            return base.Channel.SetMensajeAlerta(RqtMensajeAlerta);
        }
        
        public WebGdoc.DigitalizacionServRef.LMensajeAlertaResponse GetMensajAlerta(WebGdoc.DigitalizacionServRef.MensajeAlertaRequest RqtMensAlert) {
            return base.Channel.GetMensajAlerta(RqtMensAlert);
        }
        
        public WebGdoc.DigitalizacionServRef.MesaVirtualResponse GetListMesaVirtual(WebGdoc.DigitalizacionServRef.MesaVirtualRequest RqtListMesVir) {
            return base.Channel.GetListMesaVirtual(RqtListMesVir);
        }
        
        public WebGdoc.DigitalizacionServRef.InsertMesaVResponse SetMesaVirtual(ref WebGdoc.DigitalizacionServRef.MesaVirtualRequest RqtListMesVir) {
            return base.Channel.SetMesaVirtual(ref RqtListMesVir);
        }
        
        public WebGdoc.DigitalizacionServRef.InsertMesaVResponse SetMesaComent(ref WebGdoc.DigitalizacionServRef.MesaVirtualRequest RqtComentVir) {
            return base.Channel.SetMesaComent(ref RqtComentVir);
        }
        
        public WebGdoc.DigitalizacionServRef.MesaVirtualResponse GetListMesaComent(WebGdoc.DigitalizacionServRef.MesaVirtualRequest RqtListMesCom) {
            return base.Channel.GetListMesaComent(RqtListMesCom);
        }
    }
}
